Adding RemoteFXvGPUDisablement.exe LOLBin coverage
redcanaryco/atomic-red-team pull request #1341
Opened 2020-12-22 14:28 UTC by mgraeber-rc

Adding RemoteFXvGPUDisablement.exe LOLBIN coverage via AtomicTestHarnesses to T1218. Thanks for writing up this atomic test, @MHaggis!

**Details:**
RemoteFXvGPUDisablement.exe is an abusable built-in, signed PowerShell host binary. This test implements the `Invoke-ATHRemoteFXvGPUDisablementCommand` in `AtomicTestHarnesses` to supply coverage.

**Testing:**
Atomic test was tested locally. [Corresponding AtomicTestHarnesses tests](https://github.com/redcanaryco/AtomicTestHarnesses/blob/master/TestHarnesses/T1218_SignedBinaryProxyExecution/InvokeRemoteFXvGPUDisablementCommand.Tests.ps1) also ran without issue.

**Associated Issues:**
N/A

2020-12-22 17:02 UTC, MHaggis approved these changes

2020-12-22 23:50 UTC, clr2of8 requested changes
Could you add some to the description and maybe link to more info? For example, does this test do something with the default input arguments? (e.g. foo) What does it do, what should end user be looking for? How do they know if it "worked"? I can tell from the title that a lolbin is being used to execute something, but what is that something?

2020-12-23 11:00 UTC, mgraeber-rc commented
Thanks for the feedback, @clr2of8. I added some context to the test description. Let me know if you think that would suffice. `Invoke-ATHRemoteFXvGPUDisablementCommand` already incorporates all the logic required to validate successful execution.

2020-12-23 21:07 UTC, clr2of8 commented
Thanks Matt, I understand the big picture but still not the specifics for the atomic. So this test will proxy execution of a module called "foo" in the current working directory, which doesn't exist so nothing gets executed? So to make this test realistic users need to specify some other module using the input args?

2020-12-28 14:35 UTC, mgraeber-rc commented
Thanks again @clr2of8. Let me know if the additions make sense. If not, because this isn't a publicly documented LOLbin outside of its presence in AtomicTestHarnesses, I'm okay with not including this atomic test. Let me know what you think.

2020-12-28 16:18 UTC, clr2of8 approved these changes
I like it. Thanks for all the added explanation and for a new test harness on a new technique. Amazing!

2020-12-28 16:18 UTC, merged