T1552.007 - Updated dependencies in ListSecrets test
redcanaryco/atomic-red-team pull request #1559
Opened 2021-07-20 17:34 UTC by MSAdministrator

**Details:**
Updated dependencies in ListSecrets test

**Testing:**

**Associated Issues:**

2021-07-27 18:38 UTC, clr2of8 requested changes
If kubectl is not installed, the invoker likely will attempt to run the get_prereq_commands. These commands should either satisfy the prereq or inform the user that it will have to be done manually. In this case, could you update the get_prereq_command to say something like "Installation of kubectl must be done manually"

2021-07-27 19:13 UTC, clr2of8 commented
I edited it and the description, see what you think. If it looks good to you, I'll merge

2021-07-29 15:03 UTC, MSAdministrator commented
@clr2of8 I think that is straightforward 👍

2021-07-29 17:02 UTC, clr2of8 approved these changes

2021-07-29 17:02 UTC, merged