Added a new test for T1105 - cmdl32 LolBins
redcanaryco/atomic-red-team pull request #1744
Opened 2022-01-27 21:45 UTC by jayaram24

**Details:**
Adversary downloading malicious payload using cmdl32 to bypass detections.

**Testing:**
Windows 10

**Associated Issues:**
None

2022-01-28 20:19 UTC, clr2of8 requested changes
Hi there, thank you for the contribution. Before approval could you move the T1105.bat file to the src directory instead of bin. We use src for human readable files and bin for binary files. Also, I'm getting an exception when I run this atomic. Could you see about handling that? 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/22311332/151615659-a8431c7f-0b59-453a-8d75-125e900ff07d.png">

2022-01-28 22:26 UTC, jayaram24 commented
I updated the bin to src.
Unfortunately, I am not able to recreate 'the process "calculator.exe" not found' error. It works fine for me. Moreover, I was recommended to use the binary in T1055.004/bin/T1055.exe which triggers the calculator.exe. Do you think that is causing the problem for you?

2022-01-29 19:19 UTC, clr2of8 approved these changes

2022-01-29 19:19 UTC, clr2of8 commented
Thanks for moving that to src. I realized I was testing from Windows Server instead of client so that was probably the cause of the issue for me.

2022-01-29 19:20 UTC, merged