Psiphon
redcanaryco/atomic-red-team pull request #1771
Opened 2022-02-09 05:49 UTC by CyberBilly7

**Details:**

**Testing:**

**Associated Issues:**

2022-02-09 14:48 UTC, clr2of8 requested changes
Please see inline comments that will help make this new atomic easy to use. Thanks!

2022-02-09 14:48 UTC, clr2of8 commented on atomics/T1090.003/T1090.003.yaml
> +      description: backup of the pre-existing system proxy configuration
The description talks about the proxy backup file but the default value points to the bat file that does the installation.

2022-02-09 14:48 UTC, clr2of8 commented on atomics/T1090.003/T1090.003.yaml
> +      Taskkill /IM msedge.exe /f >$null 2>$null
Are the taskill's needed here since the bat file takes care of that?

2022-02-15 06:45 UTC, CyberBilly7 reviewed
Made Changes requested by clr208. Submitted for review.

2022-02-15 13:14 UTC, clr2of8 approved these changes

2022-02-15 13:14 UTC, merged