Update T1059.006 yaml -  Python pty module and spawn function used to…
redcanaryco/atomic-red-team pull request #1994
Opened 2022-06-11 04:48 UTC by ruyek-git

… spawn sh or bash

-Zero-Day Exploitation of Atlassian Confluence [CVE-2022-26134] Unauthenticated RCE vulnerability - Critical severity
As per Volexity, bash shells were launched by the Confluence web application process. It had spawned a bash process which spawned a Python process that in turn spawned a bash shell.
Reference: https://www.volexity.com/blog/2022/06/02/zero-day-exploitation-of-atlassian-confluence/

**Details:**

**Testing:**

**Associated Issues:**

2022-06-13 16:32 UTC, ruyek-git commented on atomics/T1059.006/T1059.006.yaml
> +    dependencies:
Added dependencies for python

2022-06-21 14:22 UTC, d1vious requested changes

2022-06-21 14:22 UTC, d1vious commented on atomics/T1059.006/T1059.006.yaml
> +    description: "\n-ID: T1059.006\n-Adversaries may abuse Python commands and scripts for execution. Python is a very popular scripting/programming language, with capabilities to perform many functi
Hey please clean up the spacing (remove the empty new lines) also add the description as a `|` .. see:

```
    description: |
      Adversaries may abuse Python commands and scripts for execution. Python is a very popular scripting/programming language, with capabilities to perform many functions. Python can be executed interactively from the command-line (via the python.exe interpreter) or via scripts (.py) that can be written and distributed to different systems. Python code can also be compiled into binary executables.\nPython comes with many built-in packages to interact with the underlying system, such as file operations and device I/O. Adversaries can use these libraries to download and execute commands or other scripts as well as perform various malicious behaviors.\n-Zero-Day Exploitation of Atlassian Confluence [CVE-2022-26134] Unauthenticated RCE vulnerability - Critical severity\nAs per Volexity, bash shells were launched by the Confluence web application process. It had spawned a bash process which spawned a Python process that in turn spawned a bash shell.\nReference: https://www.volexity.com/blog/2022/06/02/zero-day-exploitation-of-atlassian-confluence/
```

Also

The atomic successfully spawns a shell `python -c "import pty;pty.spawn('/bin/sh')"`, but it does not seem to exiting and thus the atomic times out (see pic attached). I tried adding a exit at the end, but that did not help. If we can add an exit that would be great, otherwise timeout works ok.

![image](https://user-images.githubusercontent.com/1476868/174823004-bf68a29d-3ac3-48b1-b4f6-9b11977b3151.png)

2022-06-21 22:59 UTC, ruyek-git commented
![atom](https://user-images.githubusercontent.com/107167346/174910350-b8dd35e2-4c5b-4e55-ad72-db987005ca88.png)

2022-06-25 22:29 UTC, d1vious approved these changes

2022-06-25 22:33 UTC, d1vious commented
hey @ruyek-git looks like there is a error here which is making CI fail https://github.com/redcanaryco/atomic-red-team/runs/7056783030?check_suite_focus=true#step:4:68.. specifically on line 158, I think it needs to be indented https://github.com/redcanaryco/atomic-red-team/pull/1994/files#diff-898fa9698c87d6705da88df17ea4d97f5477c5a81231d4e3d98950c95f9d9051R158

2022-06-25 22:33 UTC, d1vious requested changes

2022-06-25 22:33 UTC, d1vious commented on atomics/T1059.006/T1059.006.yaml
> +      Verify if python is in the environment variable path and attempt to import requests library.
looks like this needs to be indented, CI is failing due to it.

2022-06-25 23:56 UTC, ruyek-git commented on atomics/T1059.006/T1059.006.yaml
> +      Verify if python is in the environment variable path and attempt to import requests library.
Indentation adjusted. Thanks!

2022-06-26 00:08 UTC, d1vious approved these changes

2022-06-26 00:13 UTC, merged

2022-06-26 00:13 UTC, d1vious commented
Great work @ruyek-git and again thank you for making all the adjustments so diligently, this was a great first addition!