adding demo gif
redcanaryco/atomic-red-team pull request #2051
Opened 2022-07-27 18:46 UTC by d1vious

**Details:**
adding a simple demo video to the readme using invoke as an example for users.

**Testing:**

**Associated Issues:**

2022-07-27 20:13 UTC, patel-bhavin approved these changes

2022-07-28 23:10 UTC, clr2of8 commented
I would like to keep the README very minimal to push people to the Wiki instead. Could this go in [this section on the Wiki](https://github.com/redcanaryco/atomic-red-team/wiki/Getting-started#run-your-test)?

2022-07-28 23:10 UTC, clr2of8 requested changes
I would like to keep the README very minimal to push people to the Wiki instead. Could this go in [this section on the Wiki](https://github.com/redcanaryco/atomic-red-team/wiki/Getting-started#run-your-test)?

2022-08-03 15:04 UTC, d1vious commented
@clr2of8 removed from readme and added entry to wiki. Once this is merged the wiki will display it since it is reading from the static folder.

2022-08-03 15:17 UTC, clr2of8 approved these changes

2022-08-03 15:18 UTC, merged