Update T1562.001.yaml
redcanaryco/atomic-red-team pull request #2331
Opened 2023-02-16 10:12 UTC by tccontre

**Details:**

added several TTP's that we've seen during Awfulshred wiper analysis like:

- clearing history
- disabling history
- clearing cache
- disable swapping of device paging
- reboot system via kernel system request

**Testing:**

tested manually

**Associated Issues:**

https://cert.gov.ua/article/3718487

2023-02-22 02:41 UTC, josehelps commented
Ran the tests, and they all work as expected, awesome work @tccontre 
I added some minor suggestions to improve the documentation.

2023-02-22 03:13 UTC, josehelps requested changes

2023-02-22 08:29 UTC, tccontre commented on atomics/T1562.001/T1562.001.yaml
> +    suspend Shell History seen in Awfulshred wiper- https://unix.stackexchange.com/questions/10922/temporarily-suspend-bash-history-on-a-given-shell
thanks @josehelps noted on that

2023-02-22 08:32 UTC, tccontre commented on atomics/T1562.001/T1562.001.yaml
> +    clear pagging cache via system request. seen in Awfulshred wiper.
@josehelps thanks for this great suggestion and awesome link. I'll add this info

2023-02-22 08:37 UTC, tccontre commented on atomics/T1562.001/T1562.001.yaml
> +    disable swaaping of device paging. seen in Awfulshred wiper.
noted on this one

2023-02-23 03:19 UTC, josehelps approved these changes

2023-02-23 03:19 UTC, josehelps commented
LGTM awesome work @tccontre !

2023-02-23 03:19 UTC, merged