Add T1539 macOS Chrome Remote Debugging
redcanaryco/atomic-red-team pull request #2469
Opened 2023-06-22 17:35 UTC by jonod8698

**Details:**
New macOS test for using Chrome Remote Debugging mode to dump Chrome cookies. Chrome is started in remote debugging mode and [WhiteChocolateMacademiaNut by Justin Bui from SpectreOps](https://posts.specterops.io/hands-in-the-cookie-jar-dumping-cookies-with-chromiums-remote-debugger-port-34c4f468844e) is used to connect to the remote debugging port and dump user cookies.

**Testing:**
Installing Prerequisites
<img width="901" alt="image" src="https://github.com/redcanaryco/atomic-red-team/assets/51128479/f0158df8-06c9-49f0-ac47-8cdd741bf292">

Executing the test #1
![image](https://github.com/redcanaryco/atomic-red-team/assets/51128479/c617599b-3aee-41b2-8958-50f1bd63a438)

Executing the test #2 (consecutively)
![image](https://github.com/redcanaryco/atomic-red-team/assets/51128479/08a74231-4dca-406e-95bd-d9c423b97cbc)

Cleanup
![image](https://github.com/redcanaryco/atomic-red-team/assets/51128479/e3efbeb7-57e8-4cde-af08-844a1706ddc7)

**Associated Issues:**
N/A

2023-06-23 00:44 UTC, cyberbuff requested changes
Thanks for your first time contribution. Welcome to the project. Everything looks good. Just some minor corrections

2023-06-23 00:44 UTC, cyberbuff commented on atomics/T1539/T1539.yaml
> +      git clone https://github.com/slyd0g/WhiteChocolateMacademiaNut.git
Can you either add `cd /tmp` or clone into `/tmp/WhiteChocolateMacademiaNut` ?

2023-06-23 00:44 UTC, cyberbuff commented on atomics/T1539/T1539.yaml
> +      brew install go --force
Can you also split the requirements into two dependencies ? One to install `go` and another one to clone `WhiteChocolateMacademiaNut` ?

2023-06-25 12:51 UTC, jonod8698 commented on atomics/T1539/T1539.yaml
> +      git clone https://github.com/slyd0g/WhiteChocolateMacademiaNut.git
Done!

2023-06-25 12:51 UTC, jonod8698 commented on atomics/T1539/T1539.yaml
> +      brew install go --force
Split the two out into separate dependencies.

2023-06-26 20:38 UTC, cyberbuff approved these changes
Works great. Thanks for your contribution. Keep it up 👍

2023-06-26 20:39 UTC, merged