T1613 - Podman
redcanaryco/atomic-red-team pull request #2688
Opened 2024-02-12 19:27 UTC by W00glin

**Details:**
Tried updating `T1613` to include Podman, since there are more containers utilites outside of just Docker.

**Testing:**
I tried testing this locally on a MacOS VM using the `Invoke-AtomicTest` but kept running int o issues when trying to verifying the prereqs are met.

**Associated Issues:**
None that I can think of, nor see.

I'd also like to add, this is my first ever "real" PR on a project. I'm not a dev, so if I am doing this wrong, apologies. I read through the documentation and watched this [great video about contributing](https://www.youtube.com/watch?v=5MCtee8_s24) and wanted to add some additional checks for other container tools.

If additional info is needed, let me know and I will work on it.

2024-02-15 02:35 UTC, patel-bhavin requested changes

2024-02-15 02:35 UTC, patel-bhavin commented on atomics/T1613/T1613.yaml
> +display_name: "Docker Container and Resource Discovery"
The display name is correct here. Instead update it lower in the file :

atomic_tests:
- name:  <. >

2024-02-15 02:35 UTC, patel-bhavin commented on atomics/T1613/T1613.yaml
> +attack_technique: T1613
attack_technique, display_name -  are both top level keys. the correct yaml structure would look something like this:

---
attack_technique: T1613
display_name: "Container and Resource Discovery"
atomic_tests:
- name: Docker Container and ResourceDiscovery (update name here not above)
  <............>
- name: Podman Container and Resource Discovery
 <your new atomic>

2024-03-07 18:24 UTC, patel-bhavin commented
Thank you @W00glin ! We appreciate your first time contribution to this project. There were a few minor updates needed to make this a valid atomic yml. I have fixed up this file and the atomic looks good!

 Incase you are interested in what those changes were : https://github.com/redcanaryco/atomic-red-team/pull/2688/commits/e218a8a77508c029a85712083d069b61bef9cd58

2024-03-07 18:24 UTC, patel-bhavin approved these changes

2024-03-07 18:24 UTC, merged

2024-03-07 18:32 UTC, W00glin commented
> Thank you @W00glin ! We appreciate your first time contribution to this project. There were a few minor updates needed to make this a valid atomic yml. I have fixed up this file and the atomic looks good!
> 
> Incase you are interested in what those changes were : [e218a8a](https://github.com/redcanaryco/atomic-red-team/commit/e218a8a77508c029a85712083d069b61bef9cd58)

Glad to help. Thanks for the guidance and feedback. Really! Your contribution guide was one of the easiest to follow along with and made contributing much more simple.

As for [e218a8a](https://github.com/redcanaryco/atomic-red-team/commit/e218a8a77508c029a85712083d069b61bef9cd58), I had considered making that change but that how it was initially laid out, so I left it. Thanks for the clarification.