Update T1048.md
redcanaryco/atomic-red-team pull request #2806
Opened 2024-06-13 17:20 UTC by piotranalyst

This is a grammatically correct change.

2024-06-18 18:24 UTC, clr2of8 requested changes
The md files are automatically generated from the yaml files, to make this change please update the T1048.yaml file instead (otherwise your changes will get overwritten). Thank you.

2024-07-04 18:55 UTC, cyberbuff approved these changes

2024-07-10 15:05 UTC, clr2of8 approved these changes

2024-07-10 15:08 UTC, clr2of8 commented
Thank you for your first-time contribution. Keep it up! Don't forget to claim your free [Atomic Red Team t-shirt](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#claim-your-free-t-shirt)

2024-07-10 15:08 UTC, merged