Create T1652 folder and yaml file
redcanaryco/atomic-red-team pull request #2808
Opened 2024-06-15 05:59 UTC by enessmajlovic

**Details:**
This change creates a folder for T1652 and a yaml file inside of it with a new test case.

**Testing:**
Tested the command on a Windows 10 & 11 machine in PowerShell and it works.

**Associated Issues:**
N/A

2024-06-18 18:36 UTC, clr2of8 approved these changes
Awesome for your first-time contribution! Don't forget to claim your free [Atomic Red Team t-shirt](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#claim-your-free-t-shirt)

I noticed we have a similar test [here](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1082/T1082.md#atomic-test-28---driver-enumeration-using-driverquery) but the Technique number you have chosen (T1652) is a better fit. Do you mind making your test a little more verbose like the other I linked to and then also deleting the other one from T1082 as part of your Pull Request? I can help if you need it.

2024-06-18 18:36 UTC, clr2of8 requested changes
sorry, meant to choose "request changes"

2024-06-18 20:14 UTC, enessmajlovic commented
Hi,

I made some updates.

Let me know if everything looks good or if I need to change anything.

Thanks!

2024-06-28 23:05 UTC, clr2of8 approved these changes

2024-06-28 23:06 UTC, merged