New Test - Modify RDP-Tcp Initial Program Registry Entry
redcanaryco/atomic-red-team pull request #2861
Opened 2024-07-16 09:44 UTC by abhijose09

Modify RDP-Tcp Initial Program Registry Entry

**Details:**

**Testing:**

**Associated Issues:**

2024-07-17 02:54 UTC, clr2of8 requested changes
Awesome, could you include some cleanup commands for this one?

2024-07-17 03:59 UTC, abhijose09 commented
added cleanup command

2024-07-23 21:57 UTC, clr2of8 submitted a review, later dismissed

2024-07-23 22:06 UTC, clr2of8 approved these changes

2024-07-23 22:06 UTC, merged