Create ErrorHandler.cmd script file for test Persistence via ErrorHandler.cmd script execution
redcanaryco/atomic-red-team pull request #2896
Opened 2024-08-03 18:22 UTC by abhijose09

Added script file for new Test - Persistence via ErrorHandler.cmd script execution

**Details:**

**Testing:**

**Associated Issues:**

2024-08-13 00:11 UTC, clr2of8 requested changes
could you put this under /src instead of /bin since it is human readable? thx

2024-08-28 12:38 UTC, abhijose09 commented
made the required changes to change location of the script

2024-09-14 11:11 UTC, abhijose09 commented
the required changes have been made

2024-09-14 22:26 UTC, clr2of8 approved these changes

2024-09-14 22:27 UTC, merged