Update T1546.yaml
redcanaryco/atomic-red-team pull request #2897
Opened 2024-08-03 18:25 UTC by abhijose09

New Test - Persistence via ErrorHandler.cmd script execution

**Details:**

**Testing:**

**Associated Issues:**

2024-08-13 00:12 UTC, clr2of8 requested changes
See comment for other PR about moving to /src instead of /bin. Please update this PR to match.

2024-08-28 12:44 UTC, abhijose09 commented
made the required changes

2024-09-14 22:20 UTC, clr2of8 approved these changes

2024-09-14 22:23 UTC, clr2of8 approved these changes

2024-09-14 22:24 UTC, clr2of8 approved these changes

2024-09-14 22:25 UTC, merged