Blueteam0ps 31072024
redcanaryco/atomic-red-team pull request #2902
Opened 2024-08-10 08:03 UTC by blueteam0ps

**Details:**
Added pscp.exe based remote file copy to existing T1105
Added makecab based compression to existing T1560.001
Added an  E-mail Hiding technique in M365 by creating a new T1564.008 yaml file

**Testing:**
Tested locally. Screenshots to support execution is provided within the PR

**Associated Issues:**
None
![T1564 008](https://github.com/user-attachments/assets/6a4a02ae-b918-49ae-b39f-346194be99ec)
![T1105_33](https://github.com/user-attachments/assets/c3235c05-a596-4514-9157-3c0b40d05089)
![T1560 001_1](https://github.com/user-attachments/assets/550c9745-592c-450e-9a14-5a9ca9d65feb)
![T1560 001_2](https://github.com/user-attachments/assets/6defc026-4778-4c98-bc88-3d4c44f62a16)

2024-08-13 01:01 UTC, clr2of8 requested changes
This is amazing stuff, just a few little comments/requests for you to review. Thanks for all of your contributions!

2024-08-13 01:25 UTC, blueteam0ps reviewed
Tx Carrie. Done!

2024-08-24 18:41 UTC, clr2of8 approved these changes

2024-09-24 10:12 UTC, cyberbuff commented
Hey @blueteam0ps. Thanks for your contribution. Unfortunately I am not able to update this branch up to date with our current master branch. Whenever you get a chance, can you please update your branch so that we can merge this PR ?

2024-09-24 21:42 UTC, merged